### ISSUE TITLE
limiting how many results?

### ISSUE THREAD

**Issue by carringtny** [TheRealJAG/autocomplete#1]
This example is exactly what I needed. Do you know how I could take this and limit the list of results to only 10? I want to search mysql for everything, but based on my ordering, I only want the list to show 10 for the user.

**Comment by TheRealJAG** [comment]
In json.php change this line

$result = $mysqli->query("SELECT restaurant_name FROM restaurants where (restaurant_name like '".REQUEST."%') OR (cuisine_type like '".REQUEST."%') order by restaurant_name");

To 

$result = $mysqli->query("SELECT restaurant_name FROM restaurants where (restaurant_name like '".REQUEST."%') OR (cuisine_type like '".REQUEST."%') order by restaurant_name LIMIT 10");

For more information on LIMIT: https://www.w3schools.com/php/php_mysql_select_limit.asp

**Comment by carringtny** [comment]
That makes sense. I wasn't thinking about it from that perspective. Thanks.

**Comment by TheRealJAG** [comment]
That will limit your result set from the query which is the best place to handle the data limit. I'm sure you can create a variable and set there to be a little easier to read. I'm glad my solution worked for you. 

Let me know if I can answer any more questions for you. 

Please star the repo if it helped you in any way.
